# Generated by Django 6.0.7 on 2026-07-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Bonjour, je suis', max_length=200, verbose_name='Titre Hero (Ex: Bonjour, je suis)')),
                ('hero_name', models.CharField(default='Pape Sene', max_length=200, verbose_name='Nom Hero')),
                ('hero_subtitle', models.CharField(default='Développeur Frontend', max_length=200, verbose_name='Sous-titre Hero')),
                ('hero_description', models.TextField(verbose_name='Description Hero')),
                ('about_text', models.TextField(verbose_name="Texte 'À Propos'")),
                ('cv_url', models.CharField(default='assets/cv-pape-sene.pdf', max_length=500, verbose_name='Lien du CV')),
            ],
            options={
                'verbose_name': 'Profil Global',
                'verbose_name_plural': 'Profil Global',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie (Ex: Frontend)')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de compétence',
                'verbose_name_plural': 'Catégories de compétences',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence (Ex: React)')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order'],
            },
        ),
    ]
