# Generated by Django 6.0.7 on 2026-07-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_skillcategory_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
    ]
